#!/bin/bash

# Configuration auto-setup script
# This script generates the correct URLs based on deployment environment
# Usage: ./setup-config.sh [development|docker|production]

ENVIRONMENT=${1:-docker}
BASE_URL=${2:-}

get_env() {
  local key="$1"
  local fallback="$2"
  local value=""
  if [ -f .env ]; then
    value=$(grep -E "^${key}=" .env | tail -n 1 | cut -d '=' -f2-)
  fi
  if [ -z "$value" ]; then
    echo "$fallback"
  else
    echo "$value"
  fi
}

echo "🔧 Setting up configuration for: $ENVIRONMENT"

# Determine URLs based on environment
case $ENVIRONMENT in
  development)
    NODE_ENV="development"
    CLIENT_URL="http://localhost:5173"
    API_URL="http://localhost:4000"
    VITE_API_URL="http://localhost:4000"
    PUBLIC_URL="http://localhost:8090"
    echo "📝 Development mode:"
    echo "   Frontend: $CLIENT_URL (Vite dev server)"
    echo "   Backend: $API_URL (direct)"
    echo "   Access via: $CLIENT_URL"
    ;;
  docker)
    NODE_ENV="production"
    CLIENT_URL="http://localhost:8090"
    API_URL="http://localhost:8090"
    VITE_API_URL="/api"  # Relative path (served from nginx)
    PUBLIC_URL="http://localhost:8090"
    echo "📝 Docker mode:"
    echo "   Frontend: Served via nginx"
    echo "   Backend: http://backend:4000 (internal)"
    echo "   Access via: $CLIENT_URL"
    ;;
  production)
    NODE_ENV="production"
    if [ -n "$BASE_URL" ]; then
      CLIENT_URL="$BASE_URL"
      API_URL="$BASE_URL"
      VITE_API_URL="/api"
      PUBLIC_URL="$BASE_URL"
    else
      CLIENT_URL=$(get_env CLIENT_URL "")
      API_URL=$(get_env API_URL "")
      VITE_API_URL=$(get_env VITE_API_URL "/api")
      PUBLIC_URL=$(get_env PUBLIC_URL "")
    fi
    echo "📝 Production mode:"
    echo "   CLIENT_URL: ${CLIENT_URL:-<set in .env>}"
    echo "   API_URL: ${API_URL:-<set in .env>}"
    echo "   PUBLIC_URL: ${PUBLIC_URL:-<set in .env>}"
    ;;
  *)
    echo "Usage: ./setup-config.sh [development|docker|production]"
    exit 1
    ;;
esac

# Update .env file (preserve existing secrets if present)
echo "✏️  Updating .env file..."
JWT_SECRET_EXISTING=$(get_env JWT_SECRET "change-me-to-secure-value")
REFRESH_SECRET_EXISTING=$(get_env REFRESH_SECRET "change-me-to-another-secure-value")
POSTGRES_USER_EXISTING=$(get_env POSTGRES_USER "travel")
POSTGRES_PASSWORD_EXISTING=$(get_env POSTGRES_PASSWORD "change-this-to-a-secure-password")
POSTGRES_DB_EXISTING=$(get_env POSTGRES_DB "travel")
POSTGRES_HOST_EXISTING=$(get_env POSTGRES_HOST "postgres")
POSTGRES_PORT_EXISTING=$(get_env POSTGRES_PORT "5432")
UPLOADS_DIR_EXISTING=$(get_env UPLOADS_DIR "/app/uploads")
REDIS_URL_EXISTING=$(get_env REDIS_URL "redis://redis:6379")
SMTP_HOST_EXISTING=$(get_env SMTP_HOST "smtppro.zoho.com")
SMTP_PORT_EXISTING=$(get_env SMTP_PORT "587")
SMTP_SECURE_EXISTING=$(get_env SMTP_SECURE "false")
SMTP_USERNAME_EXISTING=$(get_env SMTP_USERNAME "your-email@domain.com")
SMTP_PASSWORD_EXISTING=$(get_env SMTP_PASSWORD "your-app-password-here")
SMTP_FROM_EXISTING=$(get_env SMTP_FROM "your-email@domain.com")
NGINX_PORT_EXISTING=$(get_env NGINX_PORT "8090")
SERVER_NAME_EXISTING=$(get_env SERVER_NAME "localhost")
POSTGRES_PORT_EXTERNAL_EXISTING=$(get_env POSTGRES_PORT_EXTERNAL "55432")
REDIS_PORT_EXTERNAL_EXISTING=$(get_env REDIS_PORT_EXTERNAL "56379")
MAILPIT_UI_PORT_EXTERNAL_EXISTING=$(get_env MAILPIT_UI_PORT_EXTERNAL "58025")
MAILPIT_SMTP_PORT_EXTERNAL_EXISTING=$(get_env MAILPIT_SMTP_PORT_EXTERNAL "51025")
FRONTEND_UPSTREAM_EXISTING=$(get_env FRONTEND_UPSTREAM "frontend:80")
BACKEND_UPSTREAM_EXISTING=$(get_env BACKEND_UPSTREAM "backend:4000")

{
  echo "# Auto-generated by setup-config.sh"
  echo "NODE_ENV=$NODE_ENV"
  echo "CLIENT_URL=$CLIENT_URL"
  echo "API_URL=$API_URL"
  echo ""
  echo "# Secrets (CHANGE THESE!)"
  echo "JWT_SECRET=${JWT_SECRET_EXISTING}"
  echo "REFRESH_SECRET=${REFRESH_SECRET_EXISTING}"
  echo ""
  echo "# Database"
  echo "POSTGRES_USER=${POSTGRES_USER_EXISTING}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD_EXISTING}"
  echo "POSTGRES_DB=${POSTGRES_DB_EXISTING}"
  echo "POSTGRES_HOST=${POSTGRES_HOST_EXISTING}"
  echo "POSTGRES_PORT=${POSTGRES_PORT_EXISTING}"
  echo "POSTGRES_PORT_EXTERNAL=${POSTGRES_PORT_EXTERNAL_EXISTING}"
  echo ""
  echo "# Frontend API URL (Vite)"
  echo "VITE_API_URL=$VITE_API_URL"
  echo ""
  echo "# Storage"
  echo "UPLOADS_DIR=${UPLOADS_DIR_EXISTING}"
  echo ""
  echo "# Redis"
  echo "REDIS_URL=${REDIS_URL_EXISTING}"
  echo "REDIS_PORT_EXTERNAL=${REDIS_PORT_EXTERNAL_EXISTING}"
  echo ""
  echo "# Email (SMTP) - set in production .env only"
  echo "SMTP_HOST=${SMTP_HOST_EXISTING}"
  echo "SMTP_PORT=${SMTP_PORT_EXISTING}"
  echo "SMTP_SECURE=${SMTP_SECURE_EXISTING}"
  echo "SMTP_USERNAME=${SMTP_USERNAME_EXISTING}"
  echo "SMTP_PASSWORD=${SMTP_PASSWORD_EXISTING}"
  echo "SMTP_FROM=${SMTP_FROM_EXISTING}"
  echo "MAILPIT_UI_PORT_EXTERNAL=${MAILPIT_UI_PORT_EXTERNAL_EXISTING}"
  echo "MAILPIT_SMTP_PORT_EXTERNAL=${MAILPIT_SMTP_PORT_EXTERNAL_EXISTING}"
  echo ""
  echo "# Public URL for external access"
  echo "PUBLIC_URL=$PUBLIC_URL"
  echo ""
  echo "# Nginx / Public Ports"
  echo "NGINX_PORT=${NGINX_PORT_EXISTING}"
  echo "SERVER_NAME=${SERVER_NAME_EXISTING}"
  echo "FRONTEND_UPSTREAM=${FRONTEND_UPSTREAM_EXISTING}"
  echo "BACKEND_UPSTREAM=${BACKEND_UPSTREAM_EXISTING}"
} > .env

# Create .env.frontend for development
if [ "$ENVIRONMENT" = "development" ]; then
  echo "✏️  Creating .env for frontend development..."
  echo "VITE_API_URL=$VITE_API_URL" > frontend/.env.development.local
  echo "VITE_APP_ENV=development" >> frontend/.env.development.local
fi

echo "✅ Configuration complete!"
echo ""
echo "📋 Configuration summary:"
echo "   Environment: $ENVIRONMENT"
echo "   NODE_ENV: $NODE_ENV"
echo "   PUBLIC_URL: $PUBLIC_URL"
