#!/bin/bash

# Configuration auto-setup script
# This script generates the correct URLs based on deployment environment
# Usage: ./setup-config.sh [development|docker|production]

ENVIRONMENT=${1:-docker}

echo "🔧 Setting up configuration for: $ENVIRONMENT"

# Determine URLs based on environment
case $ENVIRONMENT in
  development)
    NODE_ENV="development"
    CLIENT_URL="http://localhost:5173"
    API_URL="http://localhost:4000"
    VITE_API_URL="http://localhost:4000"
    PUBLIC_URL="http://localhost:8090"
    echo "📝 Development mode:"
    echo "   Frontend: $CLIENT_URL (Vite dev server)"
    echo "   Backend: $API_URL (direct)"
    echo "   Access via: $CLIENT_URL"
    ;;
  docker)
    NODE_ENV="production"
    CLIENT_URL="http://localhost:8090"
    API_URL="http://localhost:8090"
    VITE_API_URL="/api"  # Relative path (server from nginx)
    PUBLIC_URL="http://localhost:8090"
    echo "📝 Docker mode:"
    echo "   Frontend: Served via nginx"
    echo "   Backend: http://backend:4000 (internal)"
    echo "   Access via: $CLIENT_URL"
    ;;
  production)
    echo "⚠️  Production mode - using existing .env values"
    echo "   Ensure PUBLIC_URL is set correctly in .env"
    exit 0
    ;;
  *)
    echo "Usage: ./setup-config.sh [development|docker|production]"
    exit 1
    ;;
esac

# Update .env file
echo "✏️  Updating .env file..."
{
  echo "# Auto-generated by setup-config.sh"
  echo "NODE_ENV=$NODE_ENV"
  echo "CLIENT_URL=$CLIENT_URL"
  echo "API_URL=$API_URL"
  echo ""
  echo "# Secrets (CHANGE THESE!)"
  echo "JWT_SECRET=${JWT_SECRET:-change-me-to-secure-value}"
  echo "REFRESH_SECRET=${REFRESH_SECRET:-change-me-to-another-secure-value}"
  echo ""
  echo "# Database"
  echo "POSTGRES_USER=REDACTED"
  echo "POSTGRES_PASSWORD=REDACTED"
  echo "POSTGRES_DB=travel"
  echo "POSTGRES_HOST=postgres"
  echo "POSTGRES_PORT=5432"
  echo ""
  echo "# Frontend API URL (Vite)"
  echo "VITE_API_URL=$VITE_API_URL"
  echo ""
  echo "# Storage"
  echo "UPLOADS_DIR=/app/uploads"
  echo ""
  echo "# Redis"
  echo "REDIS_URL=redis://redis:6379"
  echo ""
  echo "# Email (SMTP) - set in production .env only"
  echo "SMTP_HOST=smtppro.zoho.com"
  echo "SMTP_PORT=587"
  echo "SMTP_SECURE=false"
  echo "SMTP_USERNAME=your-email@domain.com"
  echo "SMTP_PASSWORD=your-app-password-here"
  echo "SMTP_FROM=your-email@domain.com"
  echo ""
  echo "# Public URL for external access"
  echo "PUBLIC_URL=$PUBLIC_URL"
} > .env

# Create .env.frontend for development
if [ "$ENVIRONMENT" = "development" ]; then
  echo "✏️  Creating .env for frontend development..."
  echo "VITE_API_URL=$VITE_API_URL" > frontend/.env.development.local
  echo "VITE_APP_ENV=development" >> frontend/.env.development.local
fi

echo "✅ Configuration complete!"
echo ""
echo "📋 Configuration summary:"
echo "   Environment: $ENVIRONMENT"
echo "   NODE_ENV: $NODE_ENV"
echo "   PUBLIC_URL: $PUBLIC_URL"
